name: CI

on:
  pull_request_target:
    branches:
      - develop

jobs:
  yes-secrets:
    name: yes-secrets
    runs-on: ubuntu-latest
    env:
      SOME_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - name: Show secret!
        run:
          if [ $SOME_SECRET = "cabbage" ]; then echo 'match'; else echo
          'no-match'; fi

  no-secrets:
    name: no-secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SOME_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - name: Show secret!
        run:
          if [ $SOME_SECRET = "cabbage" ]; then echo 'match'; else echo
          'no-match'; fi
